version: '3.3'

services: 
  database:
    container_name: database
    image: mariadb:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - TZ=America/Bogota
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - uis_salud
  django_app:
    container_name: django_app
    depends_on:
      - database
    build: uis_salud_app    
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      DATABASE_HOST: database
    command:  bash -c "gunicorn --bind 0.0.0.0:8000  uis_salud_app.wsgi" 
    volumes:
      - static_volume:/home/app/uisalud_app/staticfiles
    networks:
      - uis_salud  
  nginx:
    image: nginx:1.21
    restart: always
    volumes:
        - static_volume:/home/app/uisalud_app/staticfiles
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    container_name: uisalud_nginx
    ports:
        - 8040:5000
    depends_on:
        - django_app
    networks:
      - uis_salud 
 

volumes:
  static_volume:

networks: 
  uis_salud:
    driver: bridge