# Generated by Django 4.1.1 on 2022-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registropaciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(auto_now=True)),
                ('glucosa', models.FloatField(blank=True, null=True)),
                ('despues_comida', models.IntegerField(blank=True, null=True)),
                ('perimetro_abdominal', models.FloatField(blank=True, null=True)),
                ('perimetro_pantorrilla', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('presionarterialdiastolica', models.IntegerField(blank=True, null=True)),
                ('presionarterialsistolica', models.IntegerField(blank=True, null=True)),
                ('paciente', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registropaciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activo', models.TextField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('correopersonal', models.CharField(max_length=255)),
                ('descripcionpersonal', models.TextField(blank=True, null=True)),
                ('fechaimagen', models.DateTimeField(blank=True, null=True)),
                ('genero', models.IntegerField()),
                ('imagenperfil', models.TextField(blank=True, null=True)),
                ('movilwhatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('primerapellido', models.CharField(max_length=255)),
                ('primernombre', models.CharField(max_length=255)),
                ('segundoapellido', models.CharField(blank=True, max_length=255, null=True)),
                ('segundonombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tokenresetcontrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(max_length=31)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostico', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
